begin;

   drop table if exists master_table, child, teenager, adult;

   create table master_table(
       id int primary key generated by default as identity ,
       age int,
       name varchar
   );

    create table child()
    inherits (master_table);

    create table teenager()
    inherits (master_table);

    create table adult()
    inherits (master_table);

    create or replace function add_to_right_table()
    returns trigger as
    $body$
        begin
            if new.age < 14 then
                insert into child values (new.id, new.age, new.name);
            elsif new.age < 18 then
                insert into teenager values (new.id, new.age, new.name);
            else
                insert into adult values (new.id, new.age, new.name);
            end if;
            return new;
        end;
        $body$
        language plpgsql;

    create trigger trg_add_to_right_table
    before insert on master_table
    for each row
    execute function add_to_right_table();

    insert into master_table (age, name)
    select random() * 100, concat('User ', number)
    from generate_series(1, 1000000) number;

end;
