begin;

    drop table if exists usr;

    create table usr(
        id int primary key generated by default as identity,
        name varchar,
        age int
    );

    INSERT INTO usr (name, age)
    select concat('User ', number),
           random() + 18
    from generate_series(1, 100) number;

    update usr
    set name = concat('NEW USER', id)
    where id > 10 and id < 20;

end;